sudo: required

services:
  - docker

before_install:
  - docker build -t sbml .

install:
  - docker run -d -p 127.0.0.1:8000:8000 sbml bash -c "python /opt/sbml/manage.py runserver 0.0.0.0:8000"

script:
  - nosetests --exe /opt/sbml
  - flake8 /opt/sbml
